-- ================================================
-- 白名单管理菜单配置SQL
-- ================================================
-- 说明：本SQL用于将"白名单管理"添加到角色菜单中
-- 使用前请先备份role表数据！
-- ================================================

-- 方法一：通过MySQL的JSON函数动态添加菜单项（推荐）
-- 这个方法会自动在"外来车辆管理"分类下添加"白名单管理"菜单

-- 步骤1：首先查看当前角色的permission配置（可选，用于确认）
-- SELECT id, name, permission FROM role;

-- 步骤2：更新管理员角色（假设ID为1，请根据实际情况调整）
-- 这个更新会在permission JSON中添加白名单管理菜单项

-- 注意：以下SQL仅供参考，实际执行前需要根据您的数据库具体情况调整

-- ================================================
-- 示例：为管理员角色添加白名单管理菜单
-- ================================================

-- 查看当前管理员角色的配置（请先执行此SQL查看现有配置）
SELECT 
    id,
    name,
    JSON_PRETTY(CAST(permission AS JSON)) as menu_config
FROM role 
WHERE name LIKE '%管理员%' OR id = 1;

-- ================================================
-- 手动配置说明
-- ================================================
-- 由于菜单配置以JSON格式存储在permission字段中，
-- 需要根据现有的菜单结构手动添加白名单管理项。
--
-- 添加位置建议：
-- 1. 可以放在"外来车辆管理"分类下，与"黑名单管理"、"月票管理"并列
-- 2. 或者放在"查询统计"分类下，与"违规查询"并列
--
-- 新增菜单项的JSON结构：
-- {
--   "id": null,
--   "sid": "77",
--   "title": "白名单管理",
--   "index": "/admin/whitelistManagement",
--   "checkedList": ["whitelistManagement"]
-- }
--
-- ================================================
-- 具体操作步骤
-- ================================================
-- 1. 使用数据库管理工具（如Navicat、DBeaver）打开role表
-- 2. 找到需要添加菜单的角色（如：管理员角色）
-- 3. 编辑permission字段（JSON格式）
-- 4. 在合适的分类（如"外来车辆管理"）的subs数组中添加上述JSON结构
-- 5. 保存并重新登录系统查看效果
--
-- ================================================
-- 示例：完整的"外来车辆管理"分类JSON（包含白名单管理）
-- ================================================
-- {
--   "id": null,
--   "sid": "4",
--   "icon": "",
--   "title": "外来车辆管理",
--   "index": "4",
--   "checkAll": false,
--   "checkedList": [],
--   "isIndeterminate": false,
--   "subs": [
--     {
--       "id": null,
--       "sid": "42",
--       "title": "外来车辆预约",
--       "index": "/admin/vehicleReservation"
--     },
--     {
--       "id": null,
--       "sid": "43",
--       "title": "车场信息管理",
--       "index": "/admin/yardInfo"
--     },
--     {
--       "id": null,
--       "sid": "44",
--       "title": "黑名单管理",
--       "index": "/admin/blackList"
--     },
--     {
--       "id": null,
--       "sid": "46",
--       "title": "月票管理",
--       "index": "/admin/monthTicket"
--     },
--     {
--       "id": null,
--       "sid": "77",
--       "title": "白名单管理",
--       "index": "/admin/whitelistManagement"
--     },
--     {
--       "id": null,
--       "sid": "45",
--       "title": "商场信息管理",
--       "index": "/admin/notifierInfo"
--     },
--     {
--       "id": null,
--       "sid": "47",
--       "title": "车辆入场记录",
--       "index": "/admin/reportCarIn"
--     },
--     {
--       "id": null,
--       "sid": "48",
--       "title": "车辆离场记录",
--       "index": "/admin/reportCarOut"
--     },
--     {
--       "id": null,
--       "sid": "49",
--       "title": "外来车辆放行管理",
--       "index": "/admin/vehicleReservationSuccess"
--     }
--   ]
-- }

-- ================================================
-- 或者：添加到"查询统计"分类
-- ================================================
-- {
--   "id": null,
--   "sid": "7",
--   "icon": "",
--   "title": "查询统计",
--   "index": "7",
--   "checkAll": false,
--   "checkedList": [],
--   "isIndeterminate": false,
--   "subs": [
--     {
--       "id": null,
--       "sid": "71",
--       "title": "预约查询",
--       "index": "/admin/appointment"
--     },
--     {
--       "id": null,
--       "sid": "72",
--       "title": "入场查询",
--       "index": "/admin/venue"
--     },
--     {
--       "id": null,
--       "sid": "76",
--       "title": "违规查询",
--       "index": "/admin/illegalRegiste"
--     },
--     {
--       "id": null,
--       "sid": "77",
--       "title": "白名单管理",
--       "index": "/admin/whitelistManagement"
--     }
--   ]
-- }

-- ================================================
-- 快捷配置脚本（针对标准配置）
-- ================================================
-- 注意：此脚本假设您的管理员角色ID为1，且permission字段结构符合上述格式
-- 执行前请务必备份数据！

-- 备份当前配置（推荐）
-- CREATE TABLE role_backup AS SELECT * FROM role WHERE id = 1;

-- 如果您的数据库支持JSON_INSERT函数，可以使用以下方式自动添加：
-- UPDATE role 
-- SET permission = JSON_ARRAY_APPEND(
--     permission,
--     '$.外来车辆管理.subs',
--     JSON_OBJECT(
--         'id', NULL,
--         'sid', '77',
--         'title', '白名单管理',
--         'index', '/admin/whitelistManagement'
--     )
-- )
-- WHERE id = 1;

-- ================================================
-- 验证配置
-- ================================================
-- 执行以下SQL验证菜单是否添加成功：
-- SELECT 
--     id,
--     name,
--     JSON_PRETTY(CAST(permission AS JSON)) as menu_config
-- FROM role 
-- WHERE id = 1;

-- ================================================
-- 注意事项
-- ================================================
-- 1. 不同角色可能有不同的菜单权限配置
-- 2. 修改后需要重新登录系统才能看到新菜单
-- 3. 确保前端路由配置正确（/admin/whitelistManagement）
-- 4. 确保WhitelistManagement.vue文件已正确创建
-- 5. sid="77"是权限标识，需要与权限管理模块对应

-- ================================================
-- 完成后的测试步骤
-- ================================================
-- 1. 重新登录后台管理系统
-- 2. 在左侧菜单中查找"白名单管理"（应该在"外来车辆管理"或"查询统计"分类下）
-- 3. 点击"白名单管理"，应该能正常打开页面
-- 4. 测试添加、编辑、删除功能
-- 5. 测试ACMS接口查询功能

-- ================================================
-- 如有问题请检查
-- ================================================
-- 1. 前端路由是否配置：/admin/whitelistManagement
-- 2. 组件文件是否存在：src/views/admin/WhitelistManagement.vue
-- 3. API接口文件是否存在：src/api/whitelist.js
-- 4. 后端接口是否正常：GET /parking/whitelist
-- 5. 数据库表是否创建：whitelist

